Global:
  checkoutpoints: null
  pretrained_model: null
  output_dir: ./output
  save_interval: -1
  dist: false
  save_interval_step: 20 
  eval_during_train: true
  eval_interval: 1
  epochs: 1024
  step_per_epoch: 600
  print_batch_step: 20
  bar_disable: true
  schedule_update_by: step
  trainer: unet_denoise

Arch:
  name: UNet
  num_classes: 3

Data:
  
  Train:
    Dataset:
      name: WaterMark
      noise_data: ../dataset/watermark/data/train/watermark_scripts/generate_images_with_watermark_for_testA
      clean_data: ../dataset/watermark/data/train/bg_pics

      clean_ops:
        - RandomCrop:
            size: 512
            padding: 128
            pad_if_needed: true
            padding_mode: reflect
        - ToTensor:
            data_format: CHW

      noise_ops:
        - RandomCrop:
            size: 512
            padding: 128
            pad_if_needed: true
            padding_mode: reflect
        - ToTensor:
            data_format: CHW
    
    DataLoader:
      num_workers: 4
      batch_sampler:
        name: DistributedBatchSampler
        batch_size: 4
        shuffle: true
        drop_last: true

Loss:
  Train:
    - PSNRLoss:
        weight: 0.01
    - MS_SSIMLoss:
        weight: 1
        data_range: 1

  Eval:
    - PSNRLoss:
        weight: 0.01
    - MS_SSIMLoss:
        weight: 1
        data_range: 1

Optimizer:
  name: Adam
  learning_rate:
    name: CosineAnnealingDecay
    T_max: 3
    learning_rate: 0.001

Metric:
  Eval:
    - PSNR:
    - MSSSIM:
        data_range: 1
    - Score: